# Generated by Django 5.2.4 on 2025-07-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('note', 'Note')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('insights', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
